#!/usr/bin/env bash
# Bash script that configures a server to ensure Nginx must be running,
# and listening on port 80 of all the server’s active IPv4 IPs

apt-get update

apt-get install -y nginx
# to replace any occurrence of "listen 8080" with "listen 80" in the default site configuration
# Check if the script is run with sudo privileges
if [ "$EUID" -ne 0 ]; then
   echo "This script must be run as root or with sudo privileges"
   exit 1
fi

# to replace any occurrence of "listen 8080" with "listen 80" in the default site configuration
vi -es /etc/nginx/sites-available/default <<-EOF
:%s/listen 8080/listen 80/g
:wq
EOF
# Restart Nginx to apply the changes
service nginx restart

