#!/usr/bin/env bash
# Check if Nginx is listening on port 80
nginx_status=$(netstat -tuln | grep ':80 ')

if [ -n "$nginx_status" ]; then
    echo "Nginx is already listening on port 80"
else
    echo "Fixing Nginx to listen on port 80..."

    # Edit Nginx configuration to listen on port 80
    sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/nginx.conf

    # Restart Nginx
    systemctl restart nginx

    # Check if Nginx is now listening on port 80
    nginx_status=$(netstat -tuln | grep ':80 ')
    if [ -n "$nginx_status" ]; then
        echo "Nginx is now listening on port 80"
    else
        echo "Failed in making Nginx listen on port 80"
        exit 1
    fi
fi

