#!/usr/bin/env bash
# bash script to should run the whoami command under the user passed as an argument
# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Run the whoami command as the specified user
sudo -u "$1" whoami
