#!/usr/bin/env bash
# bash script to run as nginx user
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown -R nginx:nginx /var/lib/nginx
sudo -u nginx service nginx start
